#!/bin/bash

build_param=$1

# verify current state
if [ -e build/state/configs-edited ];
then
    echo "[ERROR] Your testnet node is already configured."
    exit 1
fi

if [ "$build_param" == "--build" ]; then
  docker-compose -f cmds/docker/nf-testnet-setup.yml up --build
else
  docker-compose -f cmds/docker/nf-testnet-setup.yml up
fi
