#!/bin/bash

build_param=$1

if [ "$build_param" == "--build" ]; then
  docker-compose -f cmds/docker/nf-testnet-services-ALL.yml up --build
else
  docker-compose -f cmds/docker/nf-testnet-services-ALL.yml up
fi
